name: pacivic
description: A new Flutter application.

publish_to: 'RBT'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  carousel_slider: ^4.0.0
  page_transition: ^2.0.2
  introduction_screen: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  fancy_bottom_navigation: ^0.3.3
  intl: ^0.17.0
  flutter_login: ^2.2.0
  url_launcher: ^6.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.0.3
  firebase_database: ^7.1.2
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0
  timeago: ^3.0.2
  image_picker: ^0.8.2
  android_intent: ^2.0.0
  firebase_analytics: ^8.2.0
  auto_size_text: ^2.1.0
  sizer: ^0.1.3
  shared_preferences: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/logoApp.png"
  image_path_android: "assets/icons/logoApp.png"
  adaptive_icon_background: "assets/icons/logoApp.png"
  adaptive_icon_foreground: "assets/icons/logoApp.png"

flutter:

  uses-material-design: true

  assets:
    - "assets/images/"
    - "assets/images/page_state/"
    - "assets/images/page_home/"
    - "assets/icons/"

  fonts:
    - family: Poppins-R
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins-L
      fonts:
        - asset: fonts/Poppins-Light.ttf

    - family: Poppins-M
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins-B
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-EB
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf

    - family: Poppins-EL
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf

    - family: Poppins-SM
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf